### ISSUE TITLE
dependence util version is strict

### ISSUE THREAD

**Issue by AMDvsTMD** [browserify/commonjs-assert#38]
why util version 0.10.3 is strict not with caret

**Comment by jfirebaugh** [comment]
This is preventing use in the browser, because util@0.10.3 depends on inherits@2.0.1, which does not include https://github.com/isaacs/inherits/commit/8a070517edb42277a2e81d351e6a70eb37642f7b.

**Comment by BridgeAR** [comment]
This should be resolved by #44 and thus v2.0.0.

**Comment by ratoi-crysty** [comment]
Even though this is closed in the 2.0.0, the problem still persists for 1.5.x versions. Therefore we should also apply this for 1.5.x version as well, as `webpack@4.x` depends on it via `node-libs-browser`, which currently causes some issues.
